server:
  port: ${ACCOUNT_PORT}

spring:
  application:
    name: market

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jackson:
    property-naming-strategy: SNAKE_CASE

  availableDomain:
    frontendUrl: http://localhost:3000

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secretKey: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
