server:
  port: ${ACCOUNT_PORT}

spring:
  application:
    name: market

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jackson:
    property-naming-strategy: SNAKE_CASE

  availableDomain:
    frontendUrl: http://localhost:3000

  mail:
    host: smtp.gmail.com
    port: 587
    username: jyforever108@gmail.com
    password: gjma ehyi thjf wrja
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mybatis:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secretKey: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
