apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: nshm
spec:
  replicas: {{ .Values.account.replicas }}
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: {{ .Values.account.image.repository }}:{{ .Values.account.image.tag }}
        resources:
          requests:
            memory: {{ .Values.account.resources.requests.memory }}
            cpu: {{ .Values.account.resources.requests.cpu }}
          limits:
            memory: {{ .Values.account.resources.limits.memory }}
            cpu: {{ .Values.account.resources.limits.cpu }}
        envFrom:
          - secretRef:
              name: account-secret
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
