apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: account-hpa
  namespace: nshm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
