apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust
          image: locustio/locust:latest
          args:
            - "-f"
            - "/mnt/locust/locust.py"
            - "--worker"
            - "--master-host=locust-master"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: locust
              mountPath: /mnt/locust
      volumes:
        - name: locust
          configMap:
            name: locust-config
