apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config
  namespace: locust
data:
  locust.py: |
    from locust import HttpUser, task, between

    class NshmUser(HttpUser):
        wait_time = between(1, 5)

        @task
        def web_service(self):
            self.client.get("/")

        @task
        def account_service(self):
            self.client.get("/api/accounts")

        @task
        def item_service(self):
            self.client.get("/api/items")

        @task
        def wishlist_service(self):
            self.client.get("/api/wishlists")
