version: '3.8'

services:
  web:
    build:
      context: services/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "http://localhost:80" 
    # image: z1yoon/nus-secondhand-market-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    user: root
    networks:
      - local
  account:
    build:
      context: services/account
      dockerfile: Dockerfile
    # image: z1yoon/nus-secondhand-market-backend:latest
    ports:
      - "8081:8081"
    restart: always
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/postgres
      - POSTGRES_USERNAME=root
      - POSTGRES_PASSWORD=root
    depends_on:
      - postgres
    networks:
      - local

  # todo: port
  item:
    build:
      context: services/item
      dockerfile: Dockerfile.test
    environment:
      - JWT_SECRET_KEY=nshm-item-service
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=nshm
    depends_on:
      - mongo
    networks:
      - local

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=nshm
    volumes:
      - ./database/test:/docker-entrypoint-initdb.d
    networks:
      - local

  postgres:
    image: postgres:latest
    user: root
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - local


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - local

volumes:
  pgdata:

  mongo-data:


networks:
  local:
    driver: bridge  # Define a single custom network
