name: NSHM

services:
  web:
    build:
      context: services/web
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - services/web/.env
    volumes:
      - ./services/web:/app
      - /app/node_modules
    networks:
      - bridge
    depends_on:
      - account
      - item
      - wishlist
    restart: always

  account:
    build:
      context: services/account
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    env_file:
      - services/account/.env
    networks:
      - bridge
    depends_on:
      - account-db
      - rabbitmq
    restart: always

  account-db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - envs/account-db.env
    volumes:
      - ./services/account/database:/docker-entrypoint-initdb.d
    networks:
      - bridge
    restart: always

  item:
    build:
      context: services/item
      dockerfile: Dockerfile.dev
    ports:
      - 8082:8082
    env_file:
      - services/item/.env
    networks:
      - bridge
    depends_on:
      - item-db
      - rabbitmq
    restart: always

  item-db:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - envs/item-db.env
    volumes:
      - ./services/item/database/dev:/docker-entrypoint-initdb.d
    networks:
      - bridge
    restart: always

  wishlist:
    build:
      context: services/wishlist
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    env_file:
      - services/wishlist/.env
    networks:
      - bridge
    depends_on:
      - wishlist-db
      - rabbitmq
    restart: always

  wishlist-db:
    image: mongo
    ports:
      - 27018:27017
    env_file:
      - envs/wishlist-db.env
    volumes:
      - ./services/wishlist/database:/docker-entrypoint-initdb.d
    networks:
      - bridge
    restart: always

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - envs/rabbitmq.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      retries: 5
    networks:
      - bridge
    restart: always

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - bridge
    depends_on:
      - web
      - account
      - item
      - wishlist
    restart: always

volumes:
  rabbitmq_data:

networks:
  bridge:
