version: '3.8'

services:
  frontend:
    image: z1yoon/nus-secondhand-market-frontend:latest
    ports:
      - "80:3000"
    restart: always
    environment:
      - NODE_ENV=production

  backend:
    image: z1yoon/nus-secondhand-market-backend:latest
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
