services:
  frontend:
    image: z1yoon/nus-secondhand-market-frontend:latest
    ports:
      - "80:3000"
    restart: always
    environment:
      - API_BASE_URL=${API_BASE_URL}
    user: root

  backend:
    image: z1yoon/nus-secondhand-market-backend:latest
    ports:
      - "8081:8081"
    restart: always
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    user: root
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
