name: NSHM

services:
  # Database Services
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./services/account/database:/docker-entrypoint-initdb.d
    restart: always

  mongo_item:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ITEM_SERVICE_MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${ITEM_SERVICE_MONGO_DB_PASS}
      - MONGO_INITDB_DATABASE=${ITEM_SERVICE_MONGO_DB}
    volumes:
      - ./services/item/database/dev:/docker-entrypoint-initdb.d
    restart: always

  mongo_wishlist:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${WISHLIST_SERVICE_MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${WISHLIST_SERVICE_MONGO_DB_PASS}
      - MONGO_INITDB_DATABASE=${WISHLIST_SERVICE_MONGO_DB}
    volumes:
      - ./services/wishlist/database:/docker-entrypoint-initdb.d
    restart: always

  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      retries: 5
    restart: always

  # Application Services
  web:
    build:
      context: services/web
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - API_BASE_URL=${API_BASE_URL}
    env_file:
      - .env
    volumes:
      - ./services/web:/app
      - /app/node_modules
    restart: always

  account:
    build:
      context: services/account
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  wishlist:
    build:
      context: services/wishlist
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - MONGO_URL=mongodb://${MONGO_WISHLIST_USER}:${MONGO_WISHLIST_PASSWORD}@mongo_wishlist:27017/${MONGO_WISHLIST_DB}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    env_file:
      - .env
    depends_on:
      - mongo_wishlist
      - rabbitmq
    restart: always

  item:
    build:
      context: services/item
      dockerfile: Dockerfile.dev
    ports:
      - 8083:8083
    environment:
      - MONGO_URL=mongodb://${MONGO_ITEM_USER}:${MONGO_ITEM_PASSWORD}@mongo_item:27017/${MONGO_ITEM_DB}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    env_file:
      - .env
    depends_on:
      - mongo_item
      - rabbitmq
    restart: always

  # Reverse Proxy
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - web
      - account
      - item
      - wishlist
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

volumes:
  rabbitmq_data:
