name: NSHM

services:
  web:
    build:
      context: services/web
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - API_BASE_URL=${API_BASE_URL}
    volumes:
      - ./services/web:/app
      - /app/node_modules
    restart: always

  account:
    build:
      context: services/account
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./services/account/database:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - web
      - account
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

volumes:
  pgdata:
