worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;


    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://web:3000;  

        }

        location /auth {
            proxy_pass http://account:8081;  
        }

        # location /currency {
        #     proxy_pass http://currency:8082;
        # }

        location /items {
            proxy_pass http://item:8083; 
        }
    }
}
