server:
  port: 8082
spring:
  application:
    name: wishlist
  jackson:
    property-naming-strategy: SNAKE_CASE

  # MongoDB Connection
  data:
    mongodb:
      host: localhost
      port: 27017
      database: nshm_wishlist
#      username: your_username  # 如果有用户名
#      password: your_password  # 如果有密码


jwt:
  secretKey: ${SECRET_KEY}
