server:
  port: ${PORT}

spring:
  application:
    name: wishlist

  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

jwt:
  secretKey: ${JWT_SECRET_KEY}
