server:
  port: 8081
spring:
  application:
    name: wishlist

# MongoDB Connection
  data:
    mongodb:
      host: localhost
      port: 27017
      database: nshm_wishlist
#      username: your_username  # 如果有用户名
#      password: your_password  # 如果有密码
