apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nshm-ingress
  namespace: nshm
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/configuration-snippet: |
       more_set_headers "X-Frame-Options: DENY";
       more_set_headers "X-XSS-Protection: 0";
       more_set_headers "X-Content-Type-Options: nosniff";
       more_set_headers "Referrer-Policy: no-referrer";
       more_set_headers "Strict-Transport-Security: max-age=15552000; includeSubDomains";
       more_set_headers "Cross-Origin-Opener-Policy: same-origin";
       more_set_headers "Cross-Origin-Embedder-Policy: require-corp";
       more_set_headers "Cross-Origin-Resource-Policy: same-origin";
       more_set_headers "X-DNS-Prefetch-Control: off";
       more_set_headers "Origin-Agent-Cluster: ?1";
       more_set_headers "X-Download-Options: noopen";
       more_set_headers "X-Permitted-Cross-Domain-Policies: none";
spec:
  ingressClassName: nginx
  rules:
    - host: www.nshm.store
      http:
        paths:
          - path: /api/(auth/.*|auth$)
            pathType: ImplementationSpecific
            backend:
              service:
                name: account
                port:
                  number: 8081
          - path: /api/(accounts/.*|accounts$)
            pathType: ImplementationSpecific
            backend:
              service:
                name: account
                port:
                  number: 8081
          - path: /api/(items$|items/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: item
                port:
                  number: 8082
          - path: /api/(wishlists$|wishlists/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: wishlist
                port:
                  number: 8083
          - path: /api/(transactions$|transactions/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: transaction
                port:
                  number: 8084
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: web
                port:
                  number: 3000
