apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nshm-ingress
  namespace: nshm
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  ingressClassName: nginx
  rules:
    - host: www.nshm.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000

          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: account
                port:
                  number: 8081
          - path: /api/items
            pathType: Prefix
            backend:
              service:
                name: item
                port:
                  number: 8082
          - path: /api/wishlists
            pathType: Prefix
            backend:
              service:
                name: wishlist
                port:
                  number: 8083
          - path: /api/notification
            pathType: Prefix
            backend:
              service:
                name: notification
                port:
                  number: 8085
          - path: /rabbitmq
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
