apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nshm-ingress
  namespace: nshm
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($host = 'www.nshm.store') {
        rewrite ^/api/auth(/|$)(.*) /auth/$2 break;
        rewrite ^/api/accounts(/|$)(.*) /accounts/$2 break;
        rewrite ^/api/items(/|$)(.*) /items/$2 break;
        rewrite ^/api/wishlists(/|$)(.*) /wishlists/$2 break;
        rewrite ^/api/notification(/|$)(.*) /notification/$2 break;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: www.nshm.store
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: account
                port:
                  number: 8081
          - path: /accounts
            pathType: Prefix
            backend:
              service:
                name: account
                port:
                  number: 8081
          - path: /items
            pathType: Prefix
            backend:
              service:
                name: item
                port:
                  number: 8082
          - path: /wishlists
            pathType: Prefix
            backend:
              service:
                name: wishlist
                port:
                  number: 8083
          - path: /notification
            pathType: Prefix
            backend:
              service:
                name: notification
                port:
                  number: 8085
          - path: /rabbitmq
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 8086
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000

