apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: nshm
spec:
  secretBackend:
    externalSecret:
      name: "rabbitmq-secret"
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  service:
    type: LoadBalancer
  persistence:
    storageClassName: gp3
    storage: 10Gi
