---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: nshm
spec:
  replicas: 3
  auth:
    username:
      existingSecret: rabbitmq-secret
      key: RABBITMQ_DEFAULT_USER
    password:
      existingSecret: rabbitmq-secret
      key: RABBITMQ_DEFAULT_PASS
  management:
    enabled: true
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  persistence:
    storageClassName: gp3
    storage: 10Gi
