apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: nshm
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
 #rabbitmq:
  additionalConfig: |
        log.console.level = info
        channel_max = 1700
        default_user= rabbitmq
        default_pass = rabbitmq
        default_user_tags.administrator = true
  service:
    type: LoadBalancer
  persistence:
    storageClassName: gp3
    storage: 10Gi
