apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: nshm
spec:
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  service:
    type: LoadBalancer
  persistence:
    storageClassName: gp3
    storage: 10Gi
