apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: nshm
spec:
  image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
  secretBackend:
    externalSecret:
      name: "rabbitmq-secret"
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  persistence:
    storageClassName: gp3
    storage: 10Gi
  podTemplate:
    spec:
      containers:
        - name: rabbitmq
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "rabbitmq-plugins enable rabbitmq_delayed_message_exchange"
