apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: nshm
type: Opaque
stringData:
  default_user.conf: |
    default_user = rabbitmq
    default_pass = rabbitmq
  host: rabbitmq.nshm.svc
  username: rabbitmq
  password: rabbitmq
  port: "5672"
  provider: rabbitmq
  type: rabbitmq
