apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  version: "1.30"
  name: nshm-eks
  region: ap-southeast-1
  tags:
    Environment: production
    Created: EKS
vpc:
  clusterEndpoints:
    publicAccess: false
    privateAccess: true
  subnets:
    private:
      ap-southeast-1a: { id: subnet-0af29b6285e5b66af }
      ap-southeast-1b: { id: subnet-0d1c95e49874593fc }
   #public:
   #  ap-southeast-1a: { id: subnet-09e4452f6471a92d1 }
   #  ap-southeast-1c: { id: subnet-0c23bd64158970e49 }
  securityGroup: sg-0800a34e14778b722
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
managedNodeGroups:
  - name: nshm-eks-workers-30
    minSize: 0
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 20
    instanceTypes:
    - t2.micro
    - t3.micro
    spot: true
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: nus-secondhand-market
    labels: {role: worker}
    tags:
      Environment: production
      Created: EKS
    iam:
      attachPolicyARNs: [
        "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
        "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
        "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
      ]
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        cloudWatch: true
        externalDNS: true
