server:
  port: 8081
spring:
  application:
    name: currency
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    property-naming-strategy: SNAKE_CASE
  docker:
    compose:
      enabled: false



currencyLayer:
  api:
    url: "http://apilayer.net/api/live"
    access-key: "9b354492600878f1b709bd865e72ce95"
    format: "1"
