services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGO_HOST=mongo  # MongoDB 主机为容器名 "mongo"
      - MONGO_PORT=27018   # 默认 MongoDB 端口
      - MONGO_DB=test_nshm_wishlist
      - MONGO_USERNAME=test_user
      - MONGO_PASSWORD=test_password
      - JWT_SECRET_KEY=test_jwt_secret_key
      - WISHLIST_PORT=8082
    depends_on:
      - mongo
    networks:
      - bridge

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=test_nshm_wishlist
      - MONGO_INITDB_ROOT_USERNAME=test_user
      - MONGO_INITDB_ROOT_PASSWORD=test_password
    ports:
      - 27018:27017
    volumes:
      - ./database/test:/docker-entrypoint-initdb.d
    networks:
      - bridge

networks:
  bridge:
