services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=test_nshm_wishlist
      - MONGO_USERNAME=test_user
      - MONGO_PASSWORD=test_password
      - JWT_SECRET_KEY=test_jwt_secret_key
      - WISHLIST_PORT=8083
    depends_on:
      - mongo
    volumes:
      - ./reports:/app/target/site/jacoco

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=test_nshm_wishlist
      - MONGO_INITDB_ROOT_USERNAME=test_user
      - MONGO_INITDB_ROOT_PASSWORD=test_password
    ports:
      - 27017:27017
    volumes:
      - ./database/test:/docker-entrypoint-initdb.d
