---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-mongo
  namespace: nshm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-mongo
  template:
    metadata:
      labels:
        app: item-mongo
    spec:
      containers:
        - name: item-mongo
          image: bitnami/mongodb:latest
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: item-mongo-secret
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
