apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-mongo
  namespace: nshm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-mongo
  template:
    metadata:
      labels:
        app: item-mongo
    spec:
      initContainers:
      - name: git-sync
        image: alpine/git:latest
        command: ["sh", "-c", "git clone https://github.com/SE-Row-1/nus-secondhand-market.git /scripts"]
        volumeMounts:
          - name: init-script
            mountPath: /scripts

      containers:
        - name: item-mongo
          image: bitnami/mongodb:latest
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: item-mongo-secret
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
              subPath: services/item/database/production

      volumes:
        - name: init-script
          emptyDir: {}
