server:
  port: 8081
spring:
  application:
    name: apps
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://autorack.proxy.rlwy.net:50281/railway
    username: postgres
    password: CKmcwyhMSjxBCthlunnybrjaIqIaSxPx