apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service
spec:
  replicas: {{ .Values.wishlist.replicas }}
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      labels:
        app: wishlist-service
    spec:
      containers:
      - name: wishlist-service
        image: {{ .Values.wishlist.image.repository }}:{{ .Values.wishlist.image.tag }}
        resources:
          requests:
            memory: {{ .Values.wishlist.resources.requests.memory }}
            cpu: {{ .Values.wishlist.resources.requests.cpu }}
          limits:
            memory: {{ .Values.wishlist.resources.limits.memory }}
            cpu: {{ .Values.wishlist.resources.limits.cpu }}

