apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-wishlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-wishlist
  template:
    metadata:
      labels:
        app: mongodb-wishlist
    spec:
      containers:
      - name: mongodb
        image: bitnami/mongodb:latest
        env:
        - name: MONGODB_ROOT_PASSWORD
          value: {{ .Values.mongodb-wishlist.auth.rootPassword }}
        - name: MONGODB_USERNAME
          value: {{ .Values.mongodb-wishlist.auth.username }}
        - name: MONGODB_PASSWORD
          value: {{ .Values.mongodb-wishlist.auth.password }}
        - name: MONGODB_DATABASE
          value: {{ .Values.mongodb-wishlist.auth.database }}
        ports:
        - containerPort: 27017

