# Account service values
account:
  image:
    repository: z1yoon/nshm-account
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Item service values
item:
  image:
    repository: z1yoon/nshm-item
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Wishlist service values
wishlist:
  image:
    repository: z1yoon/nshm-wishlist
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Web service values
web:
  image:
    repository: z1yoon/nshm-web
    tag: fffbecc034e6bf9f8fafa77bd183b464cec06548
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
# Notification service values
notification:
  image:
    repository: z1yoon/nshm-notification
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
