# Account service values
account:
  image:
    repository: z1yoon/nshm-account
    tag: 93684ae2e679d7bf76b4798f5dcc490124e29c82
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Item service values
item:
  image:
    repository: z1yoon/nshm-item
    tag: dc2c9f5175a3655840912829dde8e7ed1f64521f
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Wishlist service values
wishlist:
  image:
    repository: z1yoon/nshm-wishlist
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Web service values
web:
  image:
    repository: z1yoon/nshm-web
    tag: ad73a185e15c81b31882d8660add0cb8cd06874b
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
# Notification service values
notification:
  image:
    repository: z1yoon/nshm-notification
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
