FROM node:lts-alpine

WORKDIR /app

RUN apk add --no-cache curl libc6-compat

RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

ENV HOSTNAME=0.0.0.0

CMD ["pnpm", "run", "dev"]
