apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nshm-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: staging
            revision: staging
            namespace: nshm-staging
            valueFile: staging-values.yaml
            syncAutomated: true
          - env: main
            revision: main
            namespace: nshm-main
            valueFile: main-values.yaml
            syncAutomated: false
  template:
    metadata:
      name: nshm-{{ env }}
    spec:
      project: default
      source:
        repoURL: 'https://github.com/SE-Row-1/nus-secondhand-market.git'
        targetRevision: '{{ revision }}'
        path: helm/nshm
        helm:
          valueFiles:
            - '{{ valueFile }}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ namespace }}'
      syncPolicy:
        {{- if eq .env "staging" }}
        automated:
          prune: true
          selfHeal: true
        {{- end }}
        retry:
          limit: 3
