apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: locust-load-testing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SE-Row-1/nus-secondhand-market.git'
    targetRevision: main
    path: locust
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: locust
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
