FROM oven/bun AS build

WORKDIR /app

COPY package.json bun.lockb ./

RUN bun install --frozen-lockfile

COPY . .

RUN bun build --outdir=dist --target=node --entry-naming="[dir]/[name].mjs" ./src/index.ts

FROM node:lts-alpine AS production

WORKDIR /app

COPY --from=build /app/dist/index.mjs .

CMD ["node", "index.mjs"]
