name: nshm-item-test

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - JWT_SECRET_KEY=nshm-item-service
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=nshm
    depends_on:
      - mongo
    networks:
      - bridge

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=nshm
    volumes:
      - ./database/test:/docker-entrypoint-initdb.d
    networks:
      - bridge

networks:
  bridge:
