server:
  port: 8081
spring:
  application:
    name: market

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}


  jackson:
    property-naming-strategy: SNAKE_CASE

  availableDomain:
    frontendUrl: ${EC2_PUBLIC}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

