server:
  port: 8081
spring:
  application:
    name: market

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL}/nshm
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis:
  configuration:
    map-underscore-to-camel-case: true

currencyLayer:
  api:
    url: "http://apilayer.net/api/live"
    access-key: "9b354492600878f1b709bd865e72ce95"
    format: "1"

