apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nshm
  namespace: argocd
spec:
  project: nshm-project
  source:
    repoURL: 'https://github.com/SE-Row-1/nus-secondhand-market.git'
    targetRevision: setup-infra
    path: helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nshm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
