apiVersion: v2
name: nshm
description: A Helm chart for the NUS Secondhand Market project
version: 0.1.0
appVersion: "1.0"

dependencies:
 #- name: mongodb
 #  version: 16.0.3
 #  repository: oci://registry-1.docker.io/bitnamicharts
  - name: rabbitmq-cluster-operator
    version: 4.3.25
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: kube-prometheus-stack
    version: 65.3.1
    repository: https://prometheus-community.github.io/helm-charts
