# Global values for MongoDB and RabbitMQ

# MongoDB custom values for item service
mongodb_item:
  auth:
    enabled: true
    rootPassword: "mongodb-item-root-password"
    username: "item-user"
    password: "item-password"
    database: "item-db"
  replicaSet:
    enabled: false

# MongoDB custom values for wishlist service
mongodb_wishlist:
  auth:
    enabled: true
    rootPassword: "mongodb-wishlist-root-password"
    username: "wishlist-user"
    password: "wishlist-password"
    database: "wishlist-db"
  replicaSet:
    enabled: false

# RabbitMQ custom values
rabbitmq:
  auth:
    username: "rabbitmq-user"
    password: "rabbitmq-password"
  persistence:
    enabled: true
    size: 1Gi
  queues:
    enabled: true
    list:
      - name: wishlist
        durable: true
        arguments:
          x-message-ttl: 86400000
      - name: item
        durable: true
        arguments:
          x-message-ttl: 86400000

# Account service values
account:
  image:
    repository: z1yoon/nshm-account
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Item service values
item:
  image:
    repository: z1yoon/nshm-item
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Wishlist service values
wishlist:
  image:
    repository: z1yoon/nshm-wishlist
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Web service values
web:
  image:
    repository: z1yoon/nshm-web
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
