const mockAccounts = [
  {
    id: 1,
    nickname: "Johnny",
    avatar_url: "https://avatars.githubusercontent.com/u/78269445?v=4",
  },
  {
    id: 2,
    nickname: "JaneS",
    avatar_url: "https://avatars.githubusercontent.com/u/69978374?v=4",
  },
  {
    id: 3,
    nickname: "AlexL",
    avatar_url: "https://avatars.githubusercontent.com/u/13389461?v=4",
  },
  {
    id: 4,
    nickname: "MikeB",
    avatar_url: "https://avatars.githubusercontent.com/u/60336739?v=4",
  },
  {
    id: 5,
    nickname: "EmJ",
    avatar_url: "https://avatars.githubusercontent.com/u/83934144?v=4",
  },
] as const;

export const mockItems = [
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[0],
    name: "Vintage Lamp",
    description:
      "A beautiful vintage lamp from the 1950s, in perfect condition.",
    price: 150.0,
    photo_urls: [],
    status: 0,
    created_at: "2023-01-15T10:30:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[1],
    name: "iPhone 12",
    description: "iPhone 12 in great condition, barely used.",
    price: 900.0,
    photo_urls: [
      "https://picsum.photos/200?r=1",
      "https://picsum.photos/200?r=2",
    ],
    status: 2,
    created_at: "2023-02-01T14:15:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[3],
    name: "Gaming Laptop",
    description: "High-performance gaming laptop with RTX 3070. Barely used.",
    price: 1800.0,
    photo_urls: ["https://picsum.photos/200?r=3"],
    status: 1,
    created_at: "2023-04-05T12:00:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[4],
    name: "Mountain Bike",
    description: "Lightweight aluminum mountain bike, perfect for trails.",
    price: 750.0,
    photo_urls: ["https://picsum.photos/200?r=4"],
    status: 2,
    created_at: "2023-05-20T09:30:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[0],
    name: "Smartwatch",
    description: "Water-resistant smartwatch with heart-rate monitor and GPS.",
    price: 220.0,
    photo_urls: ["https://picsum.photos/200?r=5"],
    status: 0,
    created_at: "2023-06-10T11:15:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[1],
    name: "Bluetooth Speaker",
    description:
      "Portable Bluetooth speaker, 20-hour battery life, waterproof.",
    price: 75.0,
    photo_urls: ["https://picsum.photos/200?r=6"],
    status: 1,
    created_at: "2023-08-15T13:00:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[3],
    name: "Air Purifier",
    description: "HEPA air purifier for large rooms, 3 fan speeds.",
    price: 200.0,
    photo_urls: ["https://picsum.photos/200?r=7"],
    status: 0,
    created_at: "2023-09-20T10:00:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[4],
    name: "Leather Jacket",
    description: "Men’s leather jacket, genuine leather, worn twice.",
    price: 300.0,
    photo_urls: ["https://picsum.photos/200?r=8"],
    status: 2,
    created_at: "2023-10-01T14:20:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[0],
    name: "Vintage Lamp 1",
    description:
      "A beautiful vintage lamp from the 1950s, in perfect condition.",
    price: 150.0,
    photo_urls: [],
    status: 0,
    created_at: "2023-01-15T10:30:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[1],
    name: "iPhone 12 1",
    description: "iPhone 12 in great condition, barely used.",
    price: 900.0,
    photo_urls: [
      "https://picsum.photos/200?r=9",
      "https://picsum.photos/200?r=10",
    ],
    status: 2,
    created_at: "2023-02-01T14:15:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[3],
    name: "Gaming Laptop 1",
    description: "High-performance gaming laptop with RTX 3070. Barely used.",
    price: 1800.0,
    photo_urls: ["https://picsum.photos/200?r=11"],
    status: 1,
    created_at: "2023-04-05T12:00:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[4],
    name: "Mountain Bike 1",
    description: "Lightweight aluminum mountain bike, perfect for trails.",
    price: 750.0,
    photo_urls: ["https://picsum.photos/200?r=12"],
    status: 2,
    created_at: "2023-05-20T09:30:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[0],
    name: "Smartwatch 1",
    description: "Water-resistant smartwatch with heart-rate monitor and GPS.",
    price: 220.0,
    photo_urls: ["https://picsum.photos/200?r=13"],
    status: 0,
    created_at: "2023-06-10T11:15:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[1],
    name: "Bluetooth Speaker 1",
    description:
      "Portable Bluetooth speaker, 20-hour battery life, waterproof.",
    price: 75.0,
    photo_urls: ["https://picsum.photos/200?r=14"],
    status: 1,
    created_at: "2023-08-15T13:00:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[3],
    name: "Air Purifier 1",
    description: "HEPA air purifier for large rooms, 3 fan speeds.",
    price: 200.0,
    photo_urls: ["https://picsum.photos/200?r=15"],
    status: 0,
    created_at: "2023-09-20T10:00:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[4],
    name: "Leather Jacket 1",
    description: "Men’s leather jacket, genuine leather, worn twice.",
    price: 300.0,
    photo_urls: ["https://picsum.photos/200?r=16"],
    status: 2,
    created_at: "2023-10-01T14:20:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[0],
    name: "Vintage Lamp 2",
    description:
      "A beautiful vintage lamp from the 1950s, in perfect condition.",
    price: 150.0,
    photo_urls: [],
    status: 0,
    created_at: "2023-01-15T10:30:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[1],
    name: "iPhone 12 2",
    description: "iPhone 12 in great condition, barely used.",
    price: 900.0,
    photo_urls: [
      "https://picsum.photos/200?r=17",
      "https://picsum.photos/200?r=18",
    ],
    status: 2,
    created_at: "2023-02-01T14:15:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[3],
    name: "Gaming Laptop 2",
    description: "High-performance gaming laptop with RTX 3070. Barely used.",
    price: 1800.0,
    photo_urls: ["https://picsum.photos/200?r=19"],
    status: 1,
    created_at: "2023-04-05T12:00:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[4],
    name: "Mountain Bike 2",
    description: "Lightweight aluminum mountain bike, perfect for trails.",
    price: 750.0,
    photo_urls: ["https://picsum.photos/200?r=20"],
    status: 2,
    created_at: "2023-05-20T09:30:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[0],
    name: "Smartwatch 2",
    description: "Water-resistant smartwatch with heart-rate monitor and GPS.",
    price: 220.0,
    photo_urls: ["https://picsum.photos/200?r=21"],
    status: 0,
    created_at: "2023-06-10T11:15:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[1],
    name: "Bluetooth Speaker 2",
    description:
      "Portable Bluetooth speaker, 20-hour battery life, waterproof.",
    price: 75.0,
    photo_urls: ["https://picsum.photos/200?r=22"],
    status: 1,
    created_at: "2023-08-15T13:00:00Z",
    deleted_at: null,
  },
  {
    id: crypto.randomUUID(),
    type: "single",
    seller: mockAccounts[3],
    name: "Air Purifier 2",
    description: "HEPA air purifier for large rooms, 3 fan speeds.",
    price: 200.0,
    photo_urls: ["https://picsum.photos/200?r=23"],
    status: 0,
    created_at: "2023-09-20T10:00:00Z",
    deleted_at: null,
  },
  // {
  //   id: crypto.randomUUID(),
  //   type: "single",
  //   seller: mockAccounts[4],
  //   name: "Leather Jacket 2",
  //   description: "Men’s leather jacket, genuine leather, worn twice.",
  //   price: 300.0,
  //   photo_urls: ["https://picsum.photos/200?r=24"],
  //   status: 2,
  //   created_at: "2023-10-01T14:20:00Z",
  //   deleted_at: null,
  // },
  // {
  //   id: crypto.randomUUID(),
  //   type: "pack",
  //   seller: mockAccounts[2],
  //   name: "Give back to the community",
  //   description: "A bonus pack of my items for sale. Get a 20% discount!",
  //   discount: 0.2,
  //   status: 0,
  //   children: [
  //     {
  //       id: crypto.randomUUID(),
  //       type: "single",
  //       seller: mockAccounts[2],
  //       name: "Office Chair",
  //       description:
  //         "Ergonomic office chair with lumbar support. Used for 6 months.",
  //       price: 120.5,
  //       photo_urls: ["https://picsum.photos/200", "https://picsum.photos/200"],
  //       status: 0,
  //       created_at: "2023-03-10T08:45:00Z",
  //       deleted_at: null,
  //     },
  //     {
  //       id: crypto.randomUUID(),
  //       type: "single",
  //       seller: mockAccounts[2],
  //       name: "Electric Kettle",
  //       description:
  //         "Fast-boil electric kettle, 1.7L capacity, stainless steel.",
  //       price: 45.0,
  //       photo_urls: ["https://picsum.photos/200"],
  //       status: 0,
  //       created_at: "2023-07-05T08:10:00Z",
  //       deleted_at: null,
  //     },
  //   ],
  //   created_at: "2023-11-15T10:30:00Z",
  //   deleted_at: null,
  // },
] as const;
