apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: {{ .Values.account.replicas }}
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: {{ .Values.account.image.repository }}:{{ .Values.account.image.tag }}
        resources:
          requests:
            memory: {{ .Values.account.resources.requests.memory }}
            cpu: {{ .Values.account.resources.requests.cpu }}
          limits:
            memory: {{ .Values.account.resources.limits.memory }}
            cpu: {{ .Values.account.resources.limits.cpu }}

