server:
  port: 8082
spring:
  application:
    name: favorlist

# MongoDB Connection
  data:
    mongodb:
      host: localhost
      port: 27017
      database: your_database_name
      username: your_username  # 如果有用户名
      password: your_password  # 如果有密码
