name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-frontend:
    if: contains(github.event.head_commit.message, 'frontend') || github.event.head_commit.added | contains('frontend') || github.event.head_commit.modified | contains('frontend')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push frontend image
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: |
          docker build --cache-from $ECR_REGISTRY/frontend:$GITHUB_REF_NAME \
            -t $ECR_REGISTRY/frontend:$GITHUB_REF_NAME \
            --build-arg NODE_ENV=$NODE_ENV \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -f frontend/Dockerfile .
          docker push $ECR_REGISTRY/frontend:$GITHUB_REF_NAME

  build-backend:
    if: contains(github.event.head_commit.message, 'backend') || github.event.head_commit.added | contains('backend') || github.event.head_commit.modified | contains('backend')
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push backend image
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        run: |
          docker build --cache-from $ECR_REGISTRY/backend:$GITHUB_REF_NAME \
            -t $ECR_REGISTRY/backend:$GITHUB_REF_NAME \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -f backend/Dockerfile .
          docker push $ECR_REGISTRY/backend:$GITHUB_REF_NAME
