name: CI for item service

on:
  push:
    branches:
      - main
    paths:
      - services/item/**
  pull_request:
    branches:
      - main
    paths:
      - services/item/**

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/item

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint with TSC
        run: bun tsc

      - name: Lint with ESLint
        run: bun eslint .

  format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/item

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Check format
        run: bun prettier . --check

  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/item

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/item

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Test with coverage
        run: |
          pip3 install podman-compose
          podman --version
          podman compose --version
          podman compose -f container-compose.test.yaml up -d --build
          podman container ls -a
          podman exec nshm-item-test_api_1 bun test --coverage
