name: CI for item service

on:
  push:
    branches:
      - main
    paths:
      - services/item/**
  pull_request:
    branches:
      - main
    paths:
      - services/item/**

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/item

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint with TSC
        run: bun tsc

      - name: Lint with ESLint
        run: bun eslint .

  format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/item

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Check format
        run: bun prettier . --check

  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/item

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/item

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Podman Compose
        run: pip3 install --user podman-compose

      - name: Start testing containers
        run: podman-compose -f container-compose.test.yaml up -d

      - name: Run tests
        run: podman exec -it nshm-item-test_api_1 bun test
