name: CI for notification service

on:
  push:
    branches:
      - main
    paths:
      - services/notification/**
  pull_request:
    branches:
      - main
    paths:
      - services/notification/**

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/notification

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Lint
        run: go vet ./...

  format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/notification

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Check format
        run: gofmt -l . | grep -q . && exit 1 || exit 0

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/notification

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Test
        run: go test ./... -cover
