name: CI for wishlist service

on:
  push:
    branches:
      - NSHM-9-Set-up-environment
#     - main
#   paths:
#     - services/wishlist/**
# pull_request:
#   branches:
#     - main
#   paths:
#     - services/wishlist/**
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/wishlist

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start MongoDB using Docker
        run: |
          docker run -d --name mongo -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=test_user -e MONGO_INITDB_ROOT_PASSWORD=test_password mongo:latest
          echo "Waiting for MongoDB to start..."
          until nc -z mongo 27017; do
            sleep 1
          done

      - name: Run tests and generate coverage report
        run: mvn clean test jacoco:report
        env:
          MONGO_HOST: mongo
          MONGO_PORT: 27017
          MONGO_DB: test_nshm_wishlist
          MONGO_USERNAME: test_user
          MONGO_PASSWORD: test_password
          WISHLIST_PORT: 8082

      - name: Stop and remove MongoDB container
        run: docker stop mongo && docker rm mongo

      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml
