name: CI for wishlist service

on:
  push:
    branches:
      - NSHM-9-Set-up-environment
#     - main
#   paths:
#     - services/wishlist/**
# pull_request:
#   branches:
#     - main
#   paths:
#     - services/wishlist/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/wishlist

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven (without Checkstyle)
        run: mvn clean package -DskipTests

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/wishlist

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start containers using docker-compose
        run: docker compose -f docker-compose.test.yaml up -d

      - name: Run tests with Maven (without Checkstyle)
        run: mvn test -Dcheckstyle.skip=true

      - name: Stop and clean containers
        run: docker compose -f docker-compose.test.yaml down

      - name: Upload Test Reports
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: services/wishlist/target/surefire-reports/*
