name: CI for wishlist service

on:
  push:
    branches:
      - NSHM-9-Set-up-environment

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/wishlist

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create Docker network
        run: docker network create wishlist-network

      - name: Start MongoDB using Docker with Volumes
        run: |
          docker run -d \
            --name mongo \
            --network wishlist-network \
            -p 27017:27017 \
            -e MONGO_INITDB_ROOT_USERNAME=test_user \
            -e MONGO_INITDB_ROOT_PASSWORD=test_password \
            -v ${{ github.workspace }}/database/test:/docker-entrypoint-initdb.d \
            mongo:latest

          echo "Waiting for MongoDB to start..."
          sleep 20  # Increase wait time to ensure MongoDB is ready
          docker logs mongo

      - name: Run tests and generate coverage report
        run: |
          docker run --rm \
            --network wishlist-network \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e MONGO_HOST=mongo \
            -e MONGO_PORT=27017 \
            -e MONGO_DB=test_nshm_wishlist \
            -e MONGO_USERNAME=test_user \
            -e MONGO_PASSWORD=test_password \
            -e WISHLIST_PORT=8083 \
            -e JWT_SECRET_KEY=test_jwt_secret_key \
            maven:3.8.5-openjdk-17-slim \
            mvn clean test jacoco:report

      - name: Stop and remove MongoDB container
        run: docker stop mongo && docker rm mongo

      - name: Remove Docker network
        run: docker network rm wishlist-network

      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: services/wishlist/target/site/jacoco/jacoco.xml

