name: CI for wishlist service

on:
  push:
    branches:
      - main
    paths:
      - services/wishlist/**
  pull_request:
    branches:
      - main
    paths:
      - services/wishlist/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/wishlist

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven (without Checkstyle)
        run: mvn clean package -Dcheckstyle.skip=true

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/wishlist

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27018:27017
        options: >
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start containers
        run: docker compose -f docker-compose.test.yaml up -d

      - name: Wait for MongoDB to be ready
        run: |
          until docker exec nshm-wishlist-test-mongo-1 mongo --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
            echo "Waiting for MongoDB to be ready..."
            sleep 5
          done

      - name: Run tests with Maven (without Checkstyle)
        run: mvn test -Dcheckstyle.skip=true

      - name: Stop and clean containers
        run: docker compose -f docker-compose.test.yaml down
