name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      infra-deploy:
        required: true
        default: 'false'
        type: boolean

jobs:
  deploy:
    if: ${{ github.event.inputs.infra-deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init and Apply
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve

      - name: Get Terraform Outputs and Save Artifact
        run: |
          cd terraform/
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo $PUBLIC_IP > ec2_public_ip.txt

      - name: Upload Outputs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: terraform/*.txt
