name: Deploy Infrastructure

on:
  push:
    branches:
      - setup-infra2
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init and Apply
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve

      - name: Get EC2 Public IP and Save Artifact
        run: |
          cd terraform/
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "EC2 Public IP: $PUBLIC_IP"
          echo $PUBLIC_IP > ec2_public_ip.txt

      - name: Upload EC2 Public IP as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ec2-public-ip
          path: ec2_public_ip.txt
