name: Destroy Infrastructure

on:
  push:
    branches:
      - setup-infra2
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Input to trigger the destroy process'
        required: true
        default: 'false'
        type: boolean

jobs:
  destroy:
    if: ${{ github.event.inputs.destroy == 'true' }}  # Only runs if input 'destroy' is true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init and Destroy
        run: |
          cd terraform/
          terraform init
          terraform destroy -auto-approve
