name: GitOps

on:
  push:
    branches:
      - main
      - setup-infra

permissions:
  contents: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Filter file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.ref }}
          filters: |
            web:
              - 'services/web/**'
            account:
              - 'services/account/**'
            item:
              - 'services/item/**'
            wishlist:
              - 'services/wishlist/**'

  build:
    if: ${{ fromJson(needs.changes.outputs.services) != '' }}
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        service: ${{ fromJson(needs.changes.outputs.services) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: |
            z1yoon/nshm-${{ matrix.service }}:${{ github.sha }}
            z1yoon/nshm-${{ matrix.service }}:latest
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}

  update:
    if: ${{ fromJson(needs.changes.outputs.services) != '' }}
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        service: ${{ fromJson(needs.changes.outputs.services) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update Image Tag Values
        run: |
          chart_dir="helm"
          new_image_tag=${{ github.sha }}
          sed -i -E "s|(repository: z1yoon/nshm-${{ matrix.service }}[[:space:]]+tag: )[^\"]*|\1$new_image_tag|g" "$chart_dir/values.yaml"

      - name: Commit the changes
        run: |
          git commit -am "Updated image tags for services: ${{ matrix.service }}"
          git push
