name: GitOps

on:
  push:
    branches:
      - setup-infra
    paths:
      - 'services/web/**'
      - 'services/account/**'
      - 'services/item/**'
      - 'services/wishlist/**'

permissions:
  contents: write

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Filter file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          ref: ${{ github.ref }}
          filters: |
            web:
              - 'services/web/**'
            account:
              - 'services/account/**'
            item:
              - 'services/item/**'
            wishlist:
              - 'services/wishlist/**'

      - name: Log filter outputs
        run: |
          echo "Web changed: ${{ steps.filter.outputs.web }}"
          echo "Account changed: ${{ steps.filter.outputs.account }}"
          echo "Item changed: ${{ steps.filter.outputs.item }}"
          echo "Wishlist changed: ${{ steps.filter.outputs.wishlist }}"

      - name: List changed files
        run: |
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Set services matrix
        id: set-matrix
        run: |
          SERVICES=()
          if [[ "${{ steps.filter.outputs.web }}" == "true" ]]; then
            SERVICES+=('{"service":"web"}')
          fi
          if [[ "${{ steps.filter.outputs.account }}" == "true" ]]; then
            SERVICES+=('{"service":"account"}')
          fi
          if [[ "${{ steps.filter.outputs.item }}" == "true" ]]; then
            SERVICES+=('{"service":"item"}')
          fi
          if [[ "${{ steps.filter.outputs.wishlist }}" == "true" ]]; then
            SERVICES+=('{"service":"wishlist"}')
          fi

          if [ ${#SERVICES[@]} -eq 0 ]; then
            echo "No services have changed. Exiting..."
            exit 0 # Exit if no services have changed
          fi

          MATRIX_JSON=$(IFS=,; echo "${SERVICES[*]}")
          echo "matrix={\"include\":[${MATRIX_JSON}]}" >> $GITHUB_OUTPUT

  build-services:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix: ${{ fromJson(needs.define-matrix.outputs.matrix) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: |
            z1yoon/nshm-${{ matrix.service }}:${{ github.sha }}
            z1yoon/nshm-${{ matrix.service }}:latest
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}

  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix: ${{ fromJson(needs.define-matrix.outputs.matrix) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update Image Tag Values
        run: |
          chart_dir="helm"
          new_image_tag=${{ github.sha }}
          sed -i -E "s|(repository: z1yoon/nshm-${{ matrix.service }}[[:space:]]+tag: )[^\"]*|\1$new_image_tag|g" "$chart_dir/values.yaml"

      - name: Commit the changes
        run: |
          if ! git diff --quiet; then
            git commit -am "Updated image tags for services: ${{ matrix.service }}"
            git push
          else
            echo "No changes to commit."
          fi

