name: GitOps

on:
  push:
    branches:
      - main
      - hot-fix-build-image
    paths:
      - services/**

permissions:
  contents: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Filter file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.ref }}
          filters: |
            web:
              - 'services/web/**'
            account:
              - 'services/account/**'
            item:
              - 'services/item/**'
            wishlist:
              - 'services/wishlist/**'
            transaction:
              - 'services/transaction/**'
            notification:
              - 'services/notification/**'
            rabbitmq:
              - 'services/rabbitmq/**'

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        service: ${{ fromJson(needs.changes.outputs.services) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: |
            z1yoon/nshm-${{ matrix.service }}:${{ matrix.service }}-${{ github.sha }}
            z1yoon/nshm-${{ matrix.service }}:latest
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}

  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        service: ${{ fromJson(needs.changes.outputs.services) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update Image Tag Values
        run: |
          chart_dir="helm/nshm"
          new_image_tag=${{ matrix.service }}-${{ github.sha }}
          sed -i "/z1yoon\/nshm-${{ matrix.service }}/{n;s/tag: .*/tag: $new_image_tag/;}" $chart_dir/values.yaml
          cat $chart_dir/values.yaml

      - name: Commit the changes
        run: |
          git fetch origin
          git config --global user.email "nshm@u.nus.edu"
          git config --global user.name "nshm"
          git commit -am "chore: updated image tags for services: ${{ matrix.service }}"
          git push origin main:$GITHUB_REF_NAME --force
