name: Infrastructure Management

on:
  push:
    branches:
      - setup-infra
  workflow_dispatch:
    inputs:
      provision:
        required: true
        default: false
        type: boolean
      destroy:
        required: false
        default: false
        type: boolean

jobs:
  provision:
    if: ${{ github.event.inputs.provision == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init and Apply
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve

      - name: Get Terraform Outputs and Save Artifact
        run: |
          cd terraform/
          RDS_ENDPOINT=$(terraform output -raw db_instance_endpoint)
          RDS_PASSWORD=$(terraform output -raw db_instance_password)
          echo $RDS_ENDPOINT > rds_endpoint.txt
          echo $RDS_PASSWORD > rds_password.txt

      - name: Upload Outputs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: terraform/*.txt

  destroy:
    if: ${{ github.event.inputs.destroy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init and Destroy
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan -destroy
          terraform destroy -auto-approve
