name: Provision Infrastructure

on:
  push:
    branches:
      - main
      - NSHM-134-Add-logs-to-wishlist
  workflow_dispatch:
    inputs:
      provision:
        description: 'Would you like to provision infra resources?'
        required: true
        type: boolean

jobs:
  provision:
    if: ${{ github.event.inputs.provision }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init and Apply
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve

      - name: Get Terraform Outputs and Save Artifact
        run: |
          cd terraform/
          RDS_PASSWORD=$(terraform output -raw db_instance_password)
          echo $RDS_PASSWORD > rds_password.txt
          aws s3 cp rds_password.txt s3://nus-backend-terraform
